In [2]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("../plantes.db")

# Voir toutes les plantes
df = pd.read_sql("SELECT * FROM plantes", conn)
display(df)

,id,url,nom_complet,nom_commun,nom_latin,hauteur,hauteur_cm_max,exposition,type_sol,rusticite,rusticite_norm,periode_floraison,couleur_fleur,feuillage,type_plante,arrosage,taille,description,prix,date_ajout
0,1,https://www.promessedefleurs.com/arbustes/arbu...,Camélia d'automne - Camellia sasanqua Yume,Camélia d'automne,Camellia sasanqua Yume,Pot de 4L/5L(Hauteur livrée env. 50/60cm),60,plantfit-fullCette plante est-elle adaptée à m...,Vivaces couvre-sols,plantfit-fullCette plante est-elle adaptée à m...,None,Vivaces à floraison printanière,Arbustes par couleur de fleur,Vivaces à feuillage persistant,Arbustes par type de climat,Bulbes de Printemps,Grands arbres à papillons,"Le Camellia sasanqua Yume, une abondante flora...","Dès39,50 €",2026-02-19
1,2,https://www.promessedefleurs.com/bulbes-d-ete/...,Collection bulbes pour Bouquets modernes blancs,Collection bulbes pour Bouquets modernes blancs,None,plantfit-fullCette plante est-elle adaptée à m...,None,plantfit-fullCette plante est-elle adaptée à m...,Vivaces couvre-sols,None,None,Vivaces à floraison printanière,Arbustes par couleur de fleur,Vivaces à feuillage persistant,Arbustes par type de climat,Bulbes de Printemps,Grands arbres à papillons,Une collection de 24 bulbes permettant de réal...,"10,43 €-30%sur le prix d'origine",2026-02-19
2,3,https://www.promessedefleurs.com/bulbes-d-ete/...,Glaïeul ou Gladiolus White Prosperity,None,Gladiolus x grandiflorus White ProsperityGlaïe...,1.20 m,None,None,None,None,None,Juillet à Septembre,"blanc, pur",None,None,None,None,Un magnifique glaieul hybride à grandes fleurs...,None,2026-02-20
3,4,https://www.promessedefleurs.com/arbustes/arbu...,Eucalyptus Baby Blue - Gommier argenté,None,Eucalyptus pulverulenta Baby BlueGommier poudr...,2.50 m,None,None,None,None,None,Mai à Juin,"blanc, -crème.",None,None,None,None,"Cet eucalyptus de petite taille, au port pyram...",None,2026-02-20
4,5,https://www.promessedefleurs.com/bulbes-de-pri...,Muscari neglectum,None,"Muscari neglectumMuscari négigé, Muscari à fle...",15 cm,None,None,None,None,None,Mars à Avril,"bleu, - noir violacé, liseré blanc.",None,None,None,None,"Une espèce botanique à floraison précoce, de f...",None,2026-02-20

In [ ]:
df=[]

Empty DataFrame
Columns: []
Index: []